services:
  dfd:
    container_name: dfd
    build: .
    ports:
      - "${DFD_HOST}:${DFD_PORT}:80"
    environment:
      DULD_API_URL: "${DULD_API_URL}"
    restart: on-failure
    logging:
      driver: journald
      options:
        tag: dfd-dfd
