services:
  feed:
    container_name: feed
    build:
      context: .
    volumes:
      - ${FEED_CONFIG_FILE}:/mnt/feed.yaml:ro
      - ${FEED_DATA_PATH}:/mnt/data:rw
      - ${FEED_WATCH_PATH}:/mnt/watch:ro
    ports:
      - "${FEED_HOST}:${FEED_PORT}:8080"
    environment:
      TZ: "Asia/Tokyo"
    restart: on-failure
    command: /app/feed.sh serve
