services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dns
    volumes:
      - ${DNS_CONFIG_PATH:?Set the dnsmasq.d folder}:/etc/dnsmasq.d:ro
    ports:
      - "${DNS_HOST_BIND_ADDRESS}:53:53/udp"
      - "${DNS_HOST_BIND_ADDRESS}:53:53/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: journald
      options:
        tag: dns-dnsmasq
