services:
  shell:
    build:
      context: .
    container_name: wdcli
    volumes:
      - ${CONFIG_PATH}:/mnt/config:ro
      - ${DATA_PATH}:/mnt/data:rw
      - ${STORAGE_PATH}:/mnt/storage:rw
    user: "${UID}:${GID}"
    command: sleep infinity
    environment:
      - TZ=${TZ:-UTC}
